### ISSUE TITLE
Add GitHub Actions for CI

### ISSUE THREAD

**Issue by nellshamrell** [Azure/azure-init#10]
Should run unit, functional (if applicable), and e2e tests

- [x] Basic GitHub Actions workflow with `cargo build` (https://github.com/Azure/azure-provisioning-agent/pull/34)
- [x] Run unit tests (https://github.com/Azure/azure-provisioning-agent/pull/34)
- [x] Run `cargo fmt` for coding style (https://github.com/Azure/azure-provisioning-agent/pull/34)
- [x] Run `cargo clippy` for linting (https://github.com/Azure/azure-provisioning-agent/pull/34)
- [ ] Run functional tests
- [ ] Run e2e tests

**Comment by dongsupark** [comment]
The remaining tasks of e2e tests should discussed and implemented in https://github.com/Azure/azure-init/issues/102.
