### ISSUE TITLE
Boot failure of functional tests with Debian-derivatives

### ISSUE THREAD

**Issue by dongsupark** [Azure/azure-init#124]
## Description

While https://github.com/Azure/azure-init/pull/108 made it already possible to specify `--groups` or env variable `AZURE_INIT_USER_GROUPS`, functional tests still fail when testing Debian-derivatives like Ubuntu, because the distros do not have the default group `wheel`.

```
azure-init: useradd: group `wheel` does not exist
Failed to start Azure-init
azure-init: Failed to create a user; none of the provided backends succeeded
```

The systemd unit [azure-init.service](https://github.com/Azure/azure-init/blob/e064a84c7203f1e43a07cdc5556f14aca5a6db58/config/azure-init.service#L5) still invokes azure-init binary without specifying custom groups with `--groups`, which results in the default value `wheel`. In case of Debian/Ubuntu, azure-init should run with `--groups admin` or similar.

A similar issue is also in [functional_tests.rs](https://github.com/Azure/azure-init/blob/e064a84c7203f1e43a07cdc5556f14aca5a6db58/tests/functional_tests.rs#L86).

**Comment by anhvoms** [comment]
We should not assume there's a group `wheel`. It's better to write to `/etc/sudoers` to give the created user sudo privilege instead of assuming any group's existence

**Comment by dongsupark** [comment]
> We should not assume there's a group `wheel`. It's better to write to `/etc/sudoers` to give the created user sudo privilege instead of assuming any group's existence

That is what `add_user_for_passwordless_sudo` is already doing. See [this](https://github.com/Azure/azure-init/blob/e064a84c7203f1e43a07cdc5556f14aca5a6db58/libazureinit/src/provision/user.rs#L217).
libazureinit seems to already do the right thing. It is rather an integration issue with functional tests.

I pushed a WIP [commit](https://github.com/dongsupark/azure-init/commit/5617456731b61b02e0d2f1025f55f81ac781d4ec), which makes functional tests pass  again with Debian/Ubuntu. But of course that is not enough.

**Comment by anhvoms** [comment]
The code by default will always add group `wheel`: [here](https://github.com/Azure/azure-init/blob/e064a84c7203f1e43a07cdc5556f14aca5a6db58/libazureinit/src/provision/user.rs#L87)

**Comment by dongsupark** [comment]
Ok, will work on the issue in 2 steps: a hotfix for removing `wheel` by default, and afterwards more functional tests for multiple distros.
