### ISSUE TITLE
image_creation.sh does not work with Azure Linux

### ISSUE THREAD

**Issue by dongsupark** [Azure/azure-init#128]
## Description

It is not possible to run `image_creation.sh` with Azure Linux (Mariner) base image. Creating VM fails like that:

```
BASE_IMAGE="MicrosoftCBLMariner:cbl-mariner:cbl-mariner-2-gen2-fips:2.20240829.01" demo/image_creation.sh
...
*********************************************************************
Creating vm testvm-1726150972 with user testuser-1726150972 in westeurope
*********************************************************************
...
vm finished deployment, waiting for image configuration to finish
vm failed to configure in 15 minutes - abort
```

I did not look into the detail.
Other distros work well: CentOS, Debian, Flatcar, Ubuntu, etc.

**Comment by anhvoms** [comment]
That's not very surprising as the customdata_template that the script uses the build the VM assumes the underlying OS uses `netplan` for networking and has `apt-get`, `dpkg`...

**Comment by dongsupark** [comment]
Yeah, that's correct. It is a non-issue.
All we need to do is a brief testing document saying `BASE_IMAGE` should be a Debian-derivative. Will soon make it.
Thanks.
