### ISSUE TITLE
[RFE] Don't hardcode distros

### ISSUE THREAD

**Issue by pothos** [Azure/azure-init#36]
## Current situation

Only select distros are supported with code like `Distributions::Debian | Distributions::Ubuntu => {`.

## Impact

Most distros don't work.

## Ideal future situation

Instead of detecting the distro and hardcoding cases, detect whether a needed command is there. E.g., if `hostnamectl` is there, use it, if not, write to `/etc/hostname` directly. Similar for adding users: While there are preferred user commands for some distros, there are common ones to use otherwise, and when nothing was found, writing to `/etc/passwd` could be tried.

**Comment by anhvoms** [comment]
I prefer keeping the distro-specific functionality instead of a lot if/else. I.e., if this tool exists, use it, otherwise use the other tool. Additionally, a tool exists in the image doesn't mean that it's the preferred tool to use for that distro. As we started adding functionality beyond hostname/username, the difference in handling each distro will start growing. 

We can solve the issue of "most distros don't work" by having a generic distro.

**Comment by t-lo** [comment]
An alternative to run-time detection would be build-time switches, i.e. give the packagers control over what tools they prefer.

**Comment by pothos** [comment]
> An alternative to run-time detection would be build-time switches, i.e. give the packagers control over what tools they prefer.

That's what Ignition does, one can tell it to run a certain binary for user adding, be it due to having a different path or because it's another tool (as long as the basic arguments are compatible). When multiple tools are supported with different arguments it's even stronger, but I would also keep the custom path setting in mind to make life easier when distros switch from sbin to bin and similar.

**Comment by dongsupark** [comment]
Rust supports a custom build-time environment variable via [rustc-env](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-env), which can be configured in `build.rs`, a custom build script. Then each environment variable can be consumed by [`env!`](https://doc.rust-lang.org/std/macro.env.html) in the compiled macro. For example, see [sudo-rs](https://github.com/memorysafety/sudo-rs/blob/90e2385b866dde529837da9e059ec0f1e9cd83c6/build.rs). That looks more or less like what ignition does like Kai said, not in Go but in Rust.

If we also want to make it possible to configure at runtime, the most wide-spread way is to use [clap](https://github.com/clap-rs/clap), which supports command-line options coupled with environment variables.

Anyway I agree that we should remove distro-specific checks in the code.

I will soon try to come up with a draft PR.
