### ISSUE TITLE
[RFE] Disable provisioning with password

### ISSUE THREAD

**Issue by anhvoms** [Azure/azure-init#52]
## Current situation
azure-init allows customers to provision Linux VMs with an admin password. 

## Impact
Password is not as secure as ssh-key. Using password leaves the VM more vulnerable to brute-force attack.

## Ideal future situation
Not supporting password provisioning.

## **Implementation options

A couple options
1) Disable password support completely. Note that Azure does allow customers to provide password to provision VM. In that case azure-init should fail provisioning if password is given.
2) Allow the customer to choose to keep password support as a compile-time configurable option (but disable it by default)

**Comment by dongsupark** [comment]
As discussed, let's bring back password provisioning only in libazureinit, as that could be used in the future for some cases.

We also have to bring back {mount,unmount}_media parts that were dropped by accident.
