### ISSUE TITLE
[RFE] Provide a mechanism to configure behavior of azure-init at runtime

### ISSUE THREAD

**Issue by anhvoms** [Azure/azure-init#65]
Currently this is not a major issue as we don't have a lot of configurable options. However, as we start adding more features to make azure-init more useful and robust (such as logging, retries), we might need to provide a way for the users to configure azure-init behavior (such as where to put logging, the level of logging that should go to console, how many minutes to retry, etc...)

We can consider providing a config file in /etc/azure-init/azure-init.conf

**Comment by dongsupark** [comment]
Done in https://github.com/Azure/azure-init/pull/137
