### ISSUE TITLE
libazureinit needs to update the sshd config when it provisions a user with password

### ISSUE THREAD

**Issue by anhvoms** [Azure/azure-init#67]
## Description

Most images by default have sshd's config PasswordAuthentication set to no. If the user indicates that disablePasswordAuthentication should be "False", we should update this field to true by writing an additional config to /etc/ssh/sshd_config.d/

Keep in mind that if the service starts later in the process, updating this config might require a restart of ssh service

**Comment by balakreddy** [comment]
Assigning this issue to myself.
