### ISSUE TITLE
Create script to run some basic e2e tests on a newly spun up Azure VM

### ISSUE THREAD

**Issue by nellshamrell** [Azure/azure-init#9]
Script should:
* Use az cli to spin up a new Ubuntu VM
* Once the VM is running, scp a locally built binary to the VM
* Install that binary
* Run basic e2e tests on the VM (either from the local dev machine or the VM itself)

**Comment by dongsupark** [comment]
Looks like it was already done by https://github.com/Azure/azure-init/pull/15.
`make e2e-test` runs the functional-test script.
